omh:
  shim:
    url: http://192.168.99.101:8084
    fakedata: true # set to true to use data in the /sample-data directory`
spring:
    data:
        mongodb:
            host: 192.168.99.101
            port: 27017
            database: omh
    batch:
        job:
            enabled: false
server:
  port: 8085
logging:
  level:
    org.springframework: INFO
  path: /var/log/metis/dpu