dataStore: mongo

application:
  url: http://192.168.99.101:8082/dsu/
internalShimServer:
  url: http://192.168.99.101:8084/

google:
  clientId: FROM_ENV
  clientSecret: FROM_ENV
  scope: email https://www.googleapis.com/auth/userinfo.profile

server:
  port: 8082
  context-path: /dsu

spring:
  application:
    name: ohmage-omh
  data:
    mongodb:
      host: 192.168.99.101
      database: omh
      port: 27017
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.101:5432/omh
    username: postgres
  jackson:
    serialization:
      INDENT_OUTPUT: true

ohmageomh:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.101:5432/ohmage
    username: postgres
    password: postgres

http:
  mappers:
    jsonPrettyPrint: true

logging:
  level:
    org.springframework: DEBUG
  path: /var/log/ohmage-auth/